before:
  hooks:
    - go mod tidy
  
builds:
  - env:
      - CGO_ENABLED=1
    binary: kaf-relay
    goos:
      - linux
    goarch:
      - amd64

archives:
  - format: tar.gz
    rlcp: true
    files:
      - config.toml.sample
      - README.md
      - LICENSE