env:
  - CGO_ENABLED=1

before:
  hooks:
  - make dist

builds:
  - binary: kaf-relay.bin
    main: .
    goos:
      - windows
      - linux
      - netbsd
    goarch:
      - amd64

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE