before:
  hooks:
    - go mod tidy
  
builds:
  - env:
      - CGO_ENABLED=1
    binary: kaf-relay
    goos:
      - windows
      - linux
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - amd64

archives:
  - format: tar.gz
    files:
      - config.toml.sample
      - README.md
      - LICENSE